### ISSUE TITLE
Selecting custom format doesn't download subtitles, metadata and doesn't follow custom naming format.

### ISSUE THREAD

**Issue by FrostedVolcano** [adithya-s-sekhar/advanced-youtube-client-ayc#10]
Hi, found another issue, although I don't know if it's a bug or intentional.

**Issue:** Videos don't have subtitles, metadata, thumbnail and custom naming when format codes are entered manually.

**Description:** Under option 8 "Show all formats" when I select option 7 "Show even more formats (Enter format code manually)" and enter the video and audio format codes, the video downloads like plain yt-dlp, I mean subtitles, metadata, thumbnail are not downloaded and the videos doesn't have custom naming format.

**Expected result:** Videos should have subtitles, metadata, thumbnail and custom naming even if format codes are entered manually.

**Comment by adithya-s-sekhar** [comment]
Wierd, It's working here, can you share this url and the formats you selected?

**Comment by FrostedVolcano** [comment]
@adithya-s-sekhar sorry for late reply again. I don't remember which video I downloaded then, but [this video](youtube.com/watch?v=YgbrG_72a3A) also shows the same behaviour. The format codes are: 271+ba. The AYC version is 4.22
![image](https://github.com/user-attachments/assets/abc5b6eb-dc9b-48d6-929a-5dc51a58603b)
The left is downloaded using yt-dlp from the terminal, it embedds thumbnail, has custom naming, the right one is downloaded using AYC (271+ba) and as you can see, it doesn't have custom naming nor thumbnail.
Thanks.

**Comment by adithya-s-sekhar** [comment]
Thanks for the heads up. The thumbnails are being embedded but windows couldn't display them due to the files having an mkv container. I changed it to mp4. You can try this build https://t.me/ayc_news/141 or here https://we.tl/t-na1GcIiZlO. Subtitles should be there as well. If anything breaks do let me know.

As for the name, it's hardcoded into the below files for youtube to fix this bug #3 . You'd have to edit them to your needs.

Or you can replace these files from dev branch
https://github.com/adithya-s-sekhar/advanced-youtube-client-ayc/blob/dev/resources/scripts/downloader/youtube.bat
https://github.com/adithya-s-sekhar/advanced-youtube-client-ayc/blob/dev/resources/scripts/downloader/ytsearch.bat

**Comment by adithya-s-sekhar** [comment]
Fixed in [v4.23](https://github.com/adithya-s-sekhar/advanced-youtube-client-ayc/releases/tag/v4.23).
